#!/usr/bin/env bash
# This script prints Best school ten times using for loop
a=1
while [ $a -le 10 ];
do
        echo "Best School"

        if [ $a -eq 9 ]
        then
                echo "Hi"
        fi
        ((a++))
done

