#!/usr/bin/env bash
# Bash scripting to check files
file=school
if [[ -e "$file" ]];
then
        echo "$file exists"
        if [[ -s "$file" ]];
        then
                echo "$file is empty"
        else
                echo "$file is not empty"
        fi

        if [[ -f "$file" ]];
        then
                echo "$file is a regular file"
        fi
else
        echo "$file does not exist"
fi
